name: kdo

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build Darwin
      env:
        GOOS: darwin
        GOARCH: amd64
      working-directory: cli/kdo
      run: go build -o bin/darwin/amd64/kdo -v .

    - name: Build Linux
      env:
        GOOS: linux
        GOARCH: amd64
      working-directory: cli/kdo
      run: go build -o bin/linux/amd64/kdo -v .

    - name: Build Windows
      env:
        GOOS: windows
        GOARCH: amd64
      working-directory: cli/kdo
      run: go build -o bin/windows/amd64/kdo.exe -v .

    - name: Test
      run: go test -v ./...
